const { contextBridge, ipcRenderer, webUtils } = require('electron');

async function call(channel, ...args) {
  const res = await ipcRenderer.invoke(channel, ...args);
  if (!res.ok) throw new Error(res.error);
  return res.value;
}

function on(channel, cb) {
  const listener = (_e, payload) => cb(payload);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
}

contextBridge.exposeInMainWorld('sprout', {
  getState: () => call('state:get'),
  getSettings: () => call('settings:get'),
  updateSettings: (patch) => call('settings:update', patch),
  updateProfile: (patch) => call('profile:update', patch),
  setApiKey: (key) => call('apikey:set', key),

  pickDocuments: () => call('docs:pick'),
  importFiles: (files) => call('docs:importPaths', Array.from(files).map((f) => webUtils.getPathForFile(f))),
  addTextDocument: (doc) => call('docs:addText', doc),
  getDocument: (id) => call('docs:get', id),
  getVoiceProfile: () => call('docs:voice'),
  updateDocument: (id, patch) => call('docs:update', id, patch),
  removeDocument: (id) => call('docs:remove', id),

  analyzeJob: (posting) => call('job:analyze', posting),
  scanScreen: () => call('job:scanScreen'),
  getApplication: (id) => call('app:get', id),
  analyzeApplication: (id) => call('app:analyze', id),
  rescoreLocal: (id) => call('app:rescoreLocal', id),
  markApplied: (id, info) => call('app:markApplied', id, info),
  exportCsv: () => call('apps:exportCsv'),
  openExternal: (url) => call('shell:openExternal', url),
  updateApplication: (id, patch) => call('app:update', id, patch),
  saveApplication: (id) => call('app:save', id),
  getResume: (id) => call('resume:get', id),
  createResume: (info) => call('resume:create', info),
  updateResume: (id, patch) => call('resume:update', id, patch),
  removeResume: (id) => call('resume:remove', id),
  removeApplication: (id) => call('app:remove', id),
  generateResume: (id) => call('app:resume', id),
  atsResume: (id) => call('app:atsResume', id),
  fixPage: (id, opts) => call('builder:fixPage', id, opts),
  baselineResume: (id) => call('builder:baseline', id),
  undoResume: (id) => call('builder:undo', id),
  generateCoverLetter: (id) => call('app:coverLetter', id),
  exportDoc: (id, which, format, editedHtml) => call('app:export', id, which, format, editedHtml),

  overlayAction: (action, appId, extra = {}) => call('overlay:action', { action, appId, ...extra }),
  saveItem: (kind, item) => call('net:save', kind, item),
  removeItem: (kind, id) => call('net:remove', kind, id),
  resetTemplates: () => call('net:resetTemplates'),
  importContacts: (text) => call('net:importContacts', text),
  importConnections: (text) => call('net:importConnections', text),
  clearConnections: () => call('net:clearConnections'),
  addConnection: (id) => call('net:addConnection', id),
  markReached: (id, info) => call('net:reached', id, info),
  setContactStatus: (id, status) => call('net:status', id, status),
  checkCareers: (ids) => call('careers:check', ids),
  markStandoutsSeen: (keys) => call('standouts:seen', keys),
  careersNotThem: (id) => call('careers:notThem', id),
  scoreCareerJob: (companyId, jobId) => call('careers:score', companyId, jobId),
  searchRole: (opts) => call('careers:searchRole', opts),
  onRoleSearchProgress: (cb) => on('role-search-progress', cb),
  saveFinderPrefs: (prefs) => call('finder:prefs', prefs),
  runFinder: (opts) => call('finder:run', opts),
  dismissFinder: (name, undo) => call('finder:dismiss', name, undo),
  clearFinder: () => call('finder:clear'),
  bridgeStatus: () => call('bridge:status'),
  getSpire: () => call('spire:get'),
  saveSpire: (run) => call('spire:save', run),
  getBank: () => call('bank:get'),
  importBullets: () => call('bank:import'),
  updateBank: (patch) => call('bank:update', patch),
  addBullet: (b) => call('bank:addBullet', b),
  updateBullet: (id, patch) => call('bank:updateBullet', id, patch),
  deleteBullet: (id) => call('bank:deleteBullet', id),
  saveRole: (role) => call('bank:saveRole', role),
  deleteRole: (id) => call('bank:deleteRole', id),
  suggestBullets: () => call('bank:suggest'),
  getEditor: (appId) => call('builder:get', appId),
  fitEditor: (appId, pages, scale, again) => call('builder:fit', appId, pages, scale, again),
  calibratePage: (scale) => call('builder:calibrate', scale),
  saveEditor: (appId, doc) => call('builder:save', appId, doc),
  autoEditor: (appId) => call('builder:auto', appId),
  roleFromBank: (appId, experienceId) => call('builder:roleFromBank', appId, experienceId),
  saveDefault: (kind, value) => call('builder:saveDefault', kind, value),
  polishBullets: (appId) => call('builder:polish', appId),
  keepWording: (appId, keys) => call('builder:keepWording', appId, keys),
  bridgeRevoke: (origin) => call('bridge:revoke', origin),
  showExtensionFolder: () => call('bridge:showFolder'),
  updateStatus: () => call('update:status'),
  checkForUpdates: () => call('update:check'),
  installUpdate: () => call('update:install'),
  overlayResize: (h) => call('overlay:resize', h),

  onStateChanged: (cb) => on('state-changed', cb),
  onAppUpdated: (cb) => on('app-updated', cb),
  onResumeProgress: (cb) => on('resume-progress', cb),
  resumeProgress: (appId) => call('resume:progress', appId),
  onToast: (cb) => on('toast', cb),
  onNavigate: (cb) => on('navigate', cb),
  onUpdateStatus: (cb) => on('update-status', cb),
  onOverlayShow: (cb) => on('overlay:show', cb),
});
